name: "Install Dependencies"
description: "Install Node.js, pnpm and project dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: '24'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
